version: 0.2
phases:
  install:
    commands:
      - npm install -g parcel-bundler
      - npm install
  build:
    commands:
      - parcel build index.ts --target=node --bundle-node-modules --no-source-maps
      - cp package.json ./dist/package.json
      - cp appspec.yaml ./dist/appspec.yaml

artifacts:
  files:
    - index.js
    - package.json
    - appspec.yaml
  base-directory: dist